export const allProductsGetQueryKey = 'allProductsGetQuery'
export const userAuthQueryKey = 'userAurhQuery'
export const userRegQueryKey = 'userRegQuery'
export const userDataGetQueryKey = 'userDataGetQuery'
export const userDataChangeQueryKey = 'userDataChangeQuery'
export const userAvatarChangeQueryKey = 'userAvatarChangeQuery'
